variant: fcos
version: 1.3.0
passwd:
  users:
    - name: vagrant
      password_hash: "$6$qeLor6il2PfKmUOI$XbwbS5/ev2YUrZqh5o7/FrWwdYxKAjbP4IoowVMnyuN.v2mbfaIB2V3dLLTHsTrEzyJDWdryf5KyZTbptxl9H0"
      ssh_authorized_keys:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key"
      groups:
        - sudo
storage:
  files:
    - path: /etc/ssh/sshd_config.d/20-allow-rsa.conf
      mode: 0644
      contents:
        inline: |
          PubkeyAcceptedKeyTypes=+ssh-rsa
